title: Homebrew Documentation
description: Documentation for the missing package manager for macOS.

remote_theme: Homebrew/brew.sh

exclude:
  - bin
  - CNAME
  - Gemfile*
  - vendor

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: :title

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/homebrew-256x256.png

logo: /assets/img/homebrew-256x256.png

twitter:
  username: MacHomebrew

facebook:
  publisher: https://www.facebook.com/machomebrew/
